""" Cracking the Coding Interview, 6th Edition - Python Solutions
8.8 Permutations with Duplicates: Write a method to compute all permutations of a string whose
characters are not necessarily unique. The list of permutations should not have duplicates.
"""
import unittest
from unittest import TestCase


def permutations_with_dups(string: str) -> list:
    """ Generate list of all permutations of a string

    Idea:
    - Very similar to 8.7 except we use a hash table to identify duplicates
    - From empty string to n characters, add each character at a time
        - For n characters, permutations can be generated by adding the nth character to all possible locations of all
        permutations of n-1 characters
        Ex. parentheses are used to emphasize pattern
        Permutations of "hi": ("hi"), ("ih")
        Permutations of "hit": ("hit", "hti", "thi"), ("iht", "ith", "tih")

    Complexity:
    - Time: O(N^2 * N!) - there are N! permutations for a N sized string. Outer for loop runs N times. Inner for loop
    runs N times for each N! permutations.
    - Space: O(N!) - store all permutations in the lists

    Approach:
    - Add each character one by one
    - For each new character, add it to every possible location in all existing permutations
    """
    perm_list = [""]
    word_table = {}
    for char in string:
        new_list = []
        for word in perm_list[:]:
            for index in range(len(word) + 1):
                new_word = word[:index] + char + word[index:]
                if new_word not in word_table:
                    word_table[new_word] = True
                    new_list.append(new_word)
        perm_list = new_list
    return perm_list


class TestPermutationsWithDups(TestCase):
    def testA(self):
        result = permutations_with_dups('fifa')
        print(len(result))
        print(result)

    def testB(self):
        result = permutations_with_dups('google')
        print(len(result))
        print(result)


if __name__ == "__main__":
    unittest.main()